var mkPlayer={api:"api.php",loadcount:20,maxerror:3,method:"POST",defaultlist:1,fadeInOut:3,autoplay:!1,coverbg:!0,mcoverbg:!1,dotshine:!1,showtime:!0,mdotshine:!1,lyrictitle:!1,homelist:!1,refreshlist:!1,autoeq:!1,desktoplyrics:!1,auxlyrics:!0,showcopyright:!0,autosource:!0,nameformat:0,volume:1,version:"2026.08.01",autoeqver:"2025.10.01",email:"gdstudio@email.com",tggroup:"https://t.me/gdstudio_music",appdir:"gdmusic.apk",appver:1.1,dldir:"DesktopLyrics.exe",proxyUrl:"https://music-proxy.gdstudio.org",
proxyBilibili:!0,auxlyricsUrl:"https://lrclib.net/api/get",bansources:["tencent","kuwo","joox"]};function applyLocalData(a){var b=playerReaddata(a);b!==""&&b!==null&&b!==void 0&&(mkPlayer[a]=b)}applyLocalData("coverbg");applyLocalData("mcoverbg");applyLocalData("lyrictitle");applyLocalData("desktoplyrics");applyLocalData("auxlyrics");applyLocalData("autosource");applyLocalData("nameformat");applyLocalData("showcopyright");applyLocalData("homelist");applyLocalData("autoeq");applyLocalData("bansources");
mkPlayer.proxyUrl.substring(mkPlayer.proxyUrl.length-1)==="/"&&(mkPlayer.proxyUrl=mkPlayer.proxyUrl.slice(0,-1));mkPlayer.auxlyricsUrl.substring(mkPlayer.auxlyricsUrl.length-1)==="/"&&(mkPlayer.auxlyricsUrl=mkPlayer.auxlyricsUrl.slice(0,-1));var rem=[];rem.prevPlayIds=[];
function audioErr(){rem.playlist!==void 0&&(rem.errCount+=1,rem.errCount>=mkPlayer.maxerror||musicList[1].item.length<=1?(layer.msg("\u8fde\u7eed\u591a\u6b21\u5931\u8d25\uff0c\u64ad\u653e\u5df2\u505c\u6b62"),rem.errCount=0):"ActiveXObject"in window&&rem.br>320?(layer.msg("IE\u4ec5\u652f\u6301MP3\u4e0eAAC\u97f3\u9891\uff0c\u64ad\u653e\u8bf7\u8c03\u4f4e\u97f3\u8d28"),rem.errCount=0):mkPlayer.autosource?(tmpLoadingMusic=layer.msg("\u64ad\u653e\u5931\u8d25\uff0c\u5c1d\u8bd5\u81ea\u52a8\u6362\u6e90",{icon:16,
shade:.01}),ajaxAutosource(musicList[rem.playlist].item[rem.playid],function(a){a&&a.url?(layer.msg(a.source+" \u6e90\u5df2\u627e\u5230\u5339\u914d\u7ed3\u679c"),rem.playlist=1,musicList[rem.playlist].item[rem.playid]=a,play(a)):(layer.msg("\u5f53\u524d\u6b4c\u66f2\u64ad\u653e\u5931\u8d25\uff0c\u81ea\u52a8\u64ad\u653e\u4e0b\u4e00\u9996"),setTimeout(function(){nextMusic()},1E3))})):(layer.msg("\u5f53\u524d\u6b4c\u66f2\u64ad\u653e\u5931\u8d25\uff0c\u81ea\u52a8\u64ad\u653e\u4e0b\u4e00\u9996"),setTimeout(function(){nextMusic()},
1E3)))}
function pause(){if(rem.paused===!1)if(mkPlayer.fadeInOut===1||mkPlayer.fadeInOut===3){clearInterval(a);setTimeout(function(){rem.paused===!1&&(clearInterval(a),rem.audio[0].pause(),setTimeout(function(){rem.audio[0].volume=volume_bar.percent},100))},500);var a=setInterval(function(){rem.audio[0].volume<=.05?(clearInterval(a),rem.audio[0].volume=0,rem.audio[0].pause(),setTimeout(function(){rem.audio[0].volume=volume_bar.percent},100)):rem.audio[0].volume-=.05},20)}else rem.audio[0].pause();else if(rem.playlist===
void 0&&listClick(0),mkPlayer.fadeInOut===2||mkPlayer.fadeInOut===3){clearInterval(b);rem.audio[0].volume=0;rem.audio[0].play();setTimeout(function(){rem.paused===!1&&(clearInterval(b),rem.audio[0].volume=volume_bar.percent)},500);var b=setInterval(function(){rem.audio[0].volume>=volume_bar.percent-.05?(clearInterval(b),rem.audio[0].volume=volume_bar.percent):rem.audio[0].volume+=.05},20)}else rem.audio[0].play()}
function orderChange(){var a=musicList[rem.playlist],b=a&&a.item?a.item[rem.playid]:void 0;orderDiv.removeClass();[1,2,3,4].indexOf(rem.order)===-1&&(rem.order=1);rem.order===1?(orderDiv.addClass("player-btn btn-order btn-order-list"),orderDiv.attr("title","\u5217\u8868\u5faa\u73af"),layer.msg("\u5217\u8868\u5faa\u73af"),rem.order=2,playerSavedata("order",rem.order)):rem.order===2?(orderDiv.addClass("player-btn btn-order btn-order-random"),orderDiv.attr("title","\u968f\u673a\u64ad\u653e"),layer.msg("\u968f\u673a\u64ad\u653e"),
rem.order=3,playerSavedata("order",rem.order)):rem.order===3&&b?(orderDiv.addClass("player-btn btn-order btn-order-embeat"),orderDiv.attr("title","Embeat\u968f\u673a"),rem.order=4,layer.open({scrollbar:!1,type:0,title:"Embeat\u968f\u673a\u6a21\u5f0f",content:'<b>\u529f\u80fd\u4ecb\u7ecd\uff1a</b><br><p>Embeat\u662fGD\u97f3\u4e50\u53f0\u81ea\u7814AI\u6a21\u578b\uff0c\u901a\u8fc7\u5206\u6790\u5f53\u524d\u97f3\u4e50\u6d41\u6d3e\u3001\u8282\u594f\u3001\u98ce\u683c\u7b49\u56e0\u7d20\uff0c\u751f\u6210\u5b9a\u5236\u5316\u63a8\u8350\u6b4c\u5355</p><b>\u2b50\ufe0f \u5b8c\u5168\u5f00\u6e90\uff0cVPS\u53ef\u90e8\u7f72\uff0c\u6b22\u8fceStar \u2b50\ufe0f</b><br><a href="https://github.com/gdstudio-org/Embeat" target="_blank">https://github.com/gdstudio-org/Embeat</a><br><br><b>AI<span style="color:green">\u5373\u5c06\u91c7\u96c6</span>\u7684\u4fe1\u606f\uff1a</b><br><p>\u5f53\u524d\u6b4c\u66f2\u4fe1\u606f</p><b>AI<span style="color:red">\u4e0d\u4f1a\u91c7\u96c6</span>\u7684\u4fe1\u606f\uff1a</b><br><p>\u60a8\u7684\u6b4c\u5355\u3001\u64ad\u653e\u5386\u53f2\u3001\u6536\u85cf\u6b4c\u66f2\u7b49</p><b>\u8bf7\u6ce8\u610f\uff1a</b><br><p>Embeat\u968f\u673a\u64ad\u653e\u6a21\u5f0f\u4e0b\uff0c<span style="color:green">\u70b9\u51fb\u5217\u8868\u4efb\u610f\u6b4c\u66f2\u5c06\u89e6\u53d1\u641c\u7d22</span>\uff0c\u5339\u914d\u7c7b\u4f3c\u98ce\u683c\u7684\u97f3\u4e50\uff0c<span style="color:red">\u76f4\u5230\u624b\u52a8\u5173\u95ed\u8be5\u6a21\u5f0f</span></p><br><b>\u662f\u5426\u5f00\u542f\u8be5\u6a21\u5f0f\uff1f</b>',
btn:["\u786e\u5b9a","\u53d6\u6d88"],btn1:function(){layer.closeAll();ajaxEmbeat(b,null)},btn2:function(){layer.close();orderChange()}})):(orderDiv.addClass("player-btn btn-order btn-order-single"),orderDiv.attr("title","\u5355\u66f2\u5faa\u73af"),layer.msg("\u5355\u66f2\u5faa\u73af"),rem.order=1,playerSavedata("order",rem.order))}
function audioPlay(){rem.paused=!1;refreshList();$(".btn-play").addClass("btn-state-paused");(mkPlayer.dotshine===!0&&!rem.isMobile||mkPlayer.mdotshine===!0&&rem.isMobile)&&$("#music-progress .mkpgb-dot").addClass("dot-move");var a=musicList[rem.playlist].item[rem.playid];if(!rem.isApp){var b=mkPlayer.nameformat===0?a.artist+" - "+a.name:mkPlayer.nameformat===1?a.name+" - "+a.artist:mkPlayer.nameformat===2?a.name:"untitled",c=isEqualizerEnabled?"[EQ] "+b:b;b&&$("#music-progress .mkpgb-title").text(b);
c&&(document.title=c)}"mediaSession"in navigator&&navigator.mediaSession.metadata&&(navigator.mediaSession.metadata.title=a.name,navigator.mediaSession.metadata.artist=a.artist,navigator.mediaSession.metadata.album=a.album);syncMediaSessionState();rem.titflash!==void 0&&clearInterval(rem.titflash);mkPlayer.autoeq!=1||audioContext||eqBoxInit();mkPlayer.desktoplyrics==1&&dlsocket&&dlsocket.readyState!==1&&connectDesktopLyric()}
function audioPause(){rem.paused=!0;$(".list-playing").removeClass("list-playing");$(".btn-play").removeClass("btn-state-paused");$("#music-progress .dot-move").removeClass("dot-move");rem.titflash!==void 0&&clearInterval(rem.titflash);rem.isApp||(document.title=rem.webTitle);dlsocket&&dlsocket.readyState===1&&dlsocket.send("");if(mkPlayer.lyrictitle){var a=musicList[rem.playlist].item[rem.playid];"mediaSession"in navigator&&navigator.mediaSession.metadata&&(navigator.mediaSession.metadata.title=
a.name,navigator.mediaSession.metadata.artist=a.artist,navigator.mediaSession.metadata.album=a.album)}syncMediaSessionState()}
function prevMusic(){rem.paused===!1&&rem.audio[0].pause();switch(rem.order?rem.order:1){case 1:playList(rem.playid);break;case 2:playList(rem.playid-1);break;case 3:if(rem.prevPlayIds.length>0)playList(rem.prevPlayIds[rem.prevPlayIds.length-1]),--rem.prevPlayIds.length;else if(musicList[1]&&musicList[1].item.length){var a=parseInt(Math.random()*musicList[1].item.length);playList(a)}break;default:playList(rem.playid-1)}}
function nextMusic(){rem.prevPlayIds[rem.prevPlayIds.length]=rem.playid;rem.prevPlayIds=rem.prevPlayIds.filter(function(c,d,e){return e.indexOf(c)===d});if(rem.prevPlayIds.length>=musicList[1].item.length){var a=rem.prevPlayIds[rem.prevPlayIds.length-1];rem.prevPlayIds=[];rem.prevPlayIds[0]=a}rem.paused===!1&&rem.audio[0].pause();switch(rem.order?rem.order:1){case 1:case 2:case 4:playList(rem.playid+1);break;case 3:if(musicList[1]&&musicList[1].item.length){for(a=0;a<5;a++){var b=parseInt(Math.random()*
musicList[1].item.length);if(rem.prevPlayIds.indexOf(b)===-1)break}playList(b)}break;default:playList(rem.playid+1)}}function autoNextMusic(){rem.order&&rem.order===1?playList(rem.playid):nextMusic()}function updateProgress(){rem.paused===!1&&(music_bar.goto(rem.audio[0].currentTime/rem.audio[0].duration),scrollLyric(rem.audio[0].currentTime))}
function listClick(a){rem.prevPlayIds=[];rem.paused===!1&&rem.audio[0].pause();rem.playlist=rem.dislist;musicList[1].item=JSON.parse(JSON.stringify(musicList[rem.playlist].item));rem.playlist===0&&(rem.playlist=1);playerSavedata("playing",musicList[1].item);refreshSheet();if(rem.order===4){var b=musicList[1];ajaxEmbeat(b&&b.item?b.item[a]:void 0,function(){musicList[1].item.length>0&&(rem.paused===!1&&rem.audio[0].pause(),playList(0))})}else playList(a)}
function playList(a){if(rem.playlist===void 0)pause();else if(!(musicList[1].item.length<=0)){a>=musicList[1].item.length&&(a=0);a<0&&(a=musicList[1].item.length-1);rem.playid=a;rem.lyric={};musicList[1].item=JSON.parse(JSON.stringify(musicList[rem.playlist].item));var b=musicList[1].item[a].source?musicList[1].item[a].source:rem.source;showLoadingDialog(b);b==="embeat"?ajaxAutosource(musicList[1].item[a],play):ajaxUrl(musicList[1].item[a],play)}}
function initAudio(){rem.audio=$("<audio></audio>").appendTo("body");mkPlayer.homelist==0&&(musicList.length=4);mkPlayer.refreshlist==1&&(playerSavedata("ulist",""),clearUserlist());rem.audio[0].volume=volume_bar.percent;rem.audio[0].addEventListener("timeupdate",updateProgress);rem.audio[0].addEventListener("play",audioPlay);rem.audio[0].addEventListener("pause",audioPause);$(rem.audio[0]).on("ended",autoNextMusic);rem.audio[0].addEventListener("error",audioErr);window.addEventListener("resize",
changePicSize);window.addEventListener?window.addEventListener("beforeunload",preventClickBack,!1):window.attachEvent&&window.attachEvent("onbeforeunload",preventClickBack);mkPlayer.desktoplyrics==1&&(rem.isApp||!window.WebSocket||"ActiveXObject"in window)&&(mkPlayer.desktoplyrics=!1);mkPlayer.desktoplyrics==1?connectDesktopLyric():dlsocket=null;"mediaSession"in navigator&&(navigator.mediaSession.metadata=new MediaMetadata,navigator.mediaSession.setActionHandler("play",pause),navigator.mediaSession.setActionHandler("pause",
pause),navigator.mediaSession.setActionHandler("previoustrack",prevMusic),navigator.mediaSession.setActionHandler("nexttrack",nextMusic),navigator.mediaSession.setActionHandler("seekbackward",null),navigator.mediaSession.setActionHandler("seekforward",null),navigator.mediaSession.setActionHandler("seekto",function(a){a.seekTime!==void 0&&rem.audio[0].duration&&mBcallback(a.seekTime/rem.audio[0].duration)}));readTextFile("notice",function(a){a=String(a).trim();if(a==="")checkHostname();else{var b=
new Date,c=b.getFullYear(),d=("0"+(b.getMonth()+1)).slice(-2);b=("0"+b.getDate()).slice(-2);c=c+d+b;rem.notice>parseInt(c)&&(rem.notice=parseInt(c));d=a.split("\n")[0].split("-");d=String(d[0]+d[1]+d[2]).trim();d.length!=8&&(d=c);var e=parseInt(d);rem.notice<e?layer.open({title:"\u516c\u544a",shade:.5,anim:0,content:a,btn:["\u4e0d\u518d\u663e\u793a","\u5e2e\u52a9"],btn1:function(){rem.notice=e;playerSavedata("notice",e);layer.closeAll();checkHostname()},btn2:function(){helpBox()}}):checkHostname()}})}
function checkHostname(){rem.hostnames.indexOf(window.location.hostname)===0?layer.msg("\u60a8\u6b63\u5728\u8bbf\u95eeGD\u97f3\u4e50\u53f0\u56fd\u9645\u7248"):rem.hostnames.indexOf(window.location.hostname)>0?layer.msg("\u60a8\u6b63\u5728\u8bbf\u95eeGD\u97f3\u4e50\u53f0\u56fd\u5185\u7248"):layer.msg("\u5f53\u524d\u7ad9\u70b9\u975eGD\u97f3\u4e50\u53f0\u5b98\u65b9\u7f51\u7ad9",{anim:6})}
function changePicSize(){var a=parseInt(window.innerWidth*1.2),b=parseInt(window.innerHeight),c=$("#blur-img").data("plugin.backgroundBlur");c&&(c.$width=a,c.$height=b);if(c=document.querySelector("#blur-img svg")){c.setAttribute("width",a);c.setAttribute("height",b);c.setAttribute("viewBox","0 0 "+a+" "+b);var d=c.querySelector("image");d&&(d.setAttribute("width",a),d.setAttribute("height",b))}rem.isMobile=isMobile.WebSize();rem.isMobile===!0?mkPlayer.coverbg===!0&&mkPlayer.mcoverbg===!1&&c&&$("#blur-img").animate({opacity:"0"},
1E3):rem.isMplayer&&dataBox("list")}function preventClickBack(a){if(a=a||window.event)a.returnValue="\u786e\u5b9a\u8981\u79bb\u5f00GD\u97f3\u4e50\u53f0\uff1f",a.preventDefault&&a.preventDefault();return"\u786e\u5b9a\u8981\u79bb\u5f00GD\u97f3\u4e50\u53f0\uff1f"}function doReload(){window.removeEventListener?window.removeEventListener("beforeunload",preventClickBack,!1):window.detachEvent&&window.detachEvent("onbeforeunload",preventClickBack);location.reload()}
function connectDesktopLyric(){dlsocket=new WebSocket("ws://127.0.0.1:8616");dlsocket.onopen=function(){console.log("Succeeded to connect desktop lyrics.");layer.msg("\u5df2\u8fde\u63a5\u684c\u9762\u6b4c\u8bcd");dlsocket.send("GD\u97f3\u4e50\u53f0 - \u684c\u9762\u6b4c\u8bcd\u5df2\u8fde\u63a5\nGDMusic - Desktop Lyrics Connected")};dlsocket.onerror=function(a){console.error("Failed to connect desktop lyrics. Please make sure the DesktopLyrics.exe is running.")}}
function syncMediaSessionState(){"mediaSession"in navigator&&(navigator.mediaSession.playbackState=rem.paused?"paused":"playing",rem.audio[0]&&rem.audio[0].duration&&rem.audio[0].duration>0&&navigator.mediaSession.setPositionState({duration:rem.audio[0].duration,playbackRate:rem.audio[0].playbackRate,position:Math.min(rem.audio[0].currentTime,rem.audio[0].duration)}))}
function play(a){tmpLoadingMusic&&(layer.close(tmpLoadingMusic),tmpLoadingMusic=null);if(a)if(a.url!="err"&&a.url!=""&&a.url!=null||a.source!="kugou"&&a.source!="joox"&&a.source!="migu"||a.br!=-2)if(a.source=="tidal"&&a.br==-3)rem.audio[0].pause(),(mkPlayer.autosource||rem.dislist==2||rem.dislist==3)&&setTimeout(function(){audioErr()},3E3),layer.msg("Tidal\u4f1a\u5458\u5df2\u8fc7\u671f\uff0c\u8bf7\u5207\u6362\u5176\u5b83\u97f3\u4e50\u6e90");else if(a.source=="qobuz"&&a.br==-3&&layer.msg("Qobuz\u4f1a\u5458\u5df2\u8fc7\u671f\uff0c\u4ec5\u63d0\u4f9b\u8bd5\u542c\u7247\u6bb5"),
a.source=="deezer"&&a.br==-3&&layer.msg("Deezer\u4f1a\u5458\u5df2\u8fc7\u671f\uff0c\u4ec5\u63d0\u4f9b\u8bd5\u542c\u7247\u6bb5"),a.source=="spotify"&&a.br==-3)rem.audio[0].pause(),(mkPlayer.autosource||rem.dislist==2||rem.dislist==3)&&setTimeout(function(){audioErr()},3E3),layer.msg("Spotify\u4f1a\u5458\u5df2\u8fc7\u671f\uff0c\u8bf7\u5207\u6362\u5176\u5b83\u97f3\u4e50\u6e90");else if(a.source=="tencent"&&a.br==-1)rem.audio[0].pause(),(mkPlayer.autosource||rem.dislist==2||rem.dislist==3)&&setTimeout(function(){audioErr()},
3E3),layer.msg("QQ\u8bf7\u6c42\u5df2\u8fbe\u4eca\u65e5\u4e0a\u9650\uff0c\u8bf7\u5207\u6362\u5176\u5b83\u97f3\u4e50\u6e90");else if(a.source=="kuwo"&&window.location.protocol==="https:"&&a.url.substr(0,6)!=="https:")rem.audio[0].pause(),(mkPlayer.autosource||rem.dislist==2||rem.dislist==3)&&setTimeout(function(){audioErr()},3E3),layer.msg("\u7531\u4e8e\u6d4f\u89c8\u5668\u9650\u5236\uff0c\u9177\u6211\u6e90\u4ec5\u4f9b\u4e0b\u8f7d");else if(a.url=="err"||a.url==""||a.url==null)rem.audio[0].pause(),audioErr();
else{addHis(a);rem.dislist==2&&rem.playlist!==2?loadList(2):refreshList();rem.onLoadedData&&(rem.audio[0].removeEventListener("loadeddata",rem.onLoadedData),rem.onLoadedData=null);try{rem.audio[0].pause(),rem.audio.attr("src",a.url),setTimeout(function(){rem.audio[0].play()},500)}catch(b){audioErr();return}rem.onLoadedData=function(){rem.audio[0].removeEventListener("loadeddata",rem.onLoadedData);rem.onLoadedData=null;musicList[1].item[rem.playid]&&musicList[1].item[rem.playid].id!==a.id||(music_bar.goto(0),
changeCover(a,!0),music_bar.lock(!1),ajaxLyric(a,lyricCallback),rem.audio[0].currentTime=0,rem.errCount=0,mkPlayer.showtime===!0&&rem.audio[0].duration&&rem.audio[0].duration>0&&$("#music-progress .mkpgb-timeright").text(formatSeconds(rem.audio[0].duration)),"mediaSession"in navigator&&rem.audio[0].duration&&rem.audio[0].duration>0&&navigator.mediaSession.setPositionState({duration:rem.audio[0].duration,playbackRate:rem.audio[0].playbackRate,position:rem.audio[0].currentTime}))};typeof rem.audio!==
"undefined"&&rem.audio[0].addEventListener("loadeddata",rem.onLoadedData)}else rem.audio[0].pause(),(mkPlayer.autosource||rem.dislist==2||rem.dislist==3)&&setTimeout(function(){audioErr()},3E3),layer.msg("\u7248\u6743\u53d7\u5730\u533a\u9650\u5236\uff0c\u8bf7\u5207\u6362\u5176\u5b83\u97f3\u4e50\u6e90");else audioErr()}
console.info("GDMusic WEB version: "+mkPlayer.version+"\nBased on open-source projects Meting & MKOnlineMusicPlayer.\nWritten by metowolf & mengkun. Fully re-written by GD Studio.\nThis platform is for study purposes only. Do NOT use it commercially!\nTo report any unlawful activity, please contact us: "+mkPlayer.email);function mBcallback(a){a>1&&(a=1);a<0&&(a=0);a*=rem.audio[0].duration;rem.audio[0].currentTime=a;refreshLyric(a);syncMediaSessionState()}
function vBcallback(a){a>1&&(a=1);a<0&&(a=0);rem.audio[0]!==void 0&&(rem.audio[0].volume=a);$("#volume-progress .mkpgb-dot").css("left",a*100+"%");$("#volume-progress .mkpgb-cur").css("width",a*100+"%");$(".btn-quiet").is(".btn-state-quiet")&&$(".btn-quiet").removeClass("btn-state-quiet");a===0&&$(".btn-quiet").addClass("btn-state-quiet");playerSavedata("volume",a)}
var initProgress=function(){music_bar=new mkpgb("#music-progress",0,mBcallback);music_bar.lock(!0);var a=playerReaddata("volume");a=a!=null?a:rem.isMobile?1:mkPlayer.volume;a<0&&(a=0);a>1&&(a=1);a==0&&$(".btn-quiet").addClass("btn-state-quiet");volume_bar=new mkpgb("#volume-progress",a,vBcallback);rem.order=playerReaddata("order");orderDiv=$(".btn-order");orderDiv.removeClass();[1,2,3,4].indexOf(rem.order)===-1?rem.order=2:rem.order===4&&(rem.order=3);rem.order===1?(orderDiv.addClass("player-btn btn-order btn-order-single"),
orderDiv.attr("title","\u5355\u66f2\u5faa\u73af")):rem.order===2?(orderDiv.addClass("player-btn btn-order btn-order-list"),orderDiv.attr("title","\u5217\u8868\u5faa\u73af")):rem.order===3&&(orderDiv.addClass("player-btn btn-order btn-order-random"),orderDiv.attr("title","\u968f\u673a\u64ad\u653e"))};mkpgb=function(a,b,c){this.bar=a;this.percent=b;this.callback=c;this.locked=!1;this.init()};
mkpgb.prototype={init:function(){function a(d){c&&(d=d.clientX<b.minLength?0:d.clientX>b.maxLength?1:(d.clientX-b.minLength)/(b.maxLength-b.minLength),b.callback(d),b.goto(d))}var b=this,c=!1;$(b.bar).html('<div class="mkpgb-title"></div><div class="mkpgb-bar"></div><div class="mkpgb-cur"></div><div class="mkpgb-dot"></div><div class="mkpgb-timeleft"></div><div class="mkpgb-timeright"></div>');$("#volume-progress .mkpgb-title").remove();$("#volume-progress .mkpgb-timeleft").remove();$("#volume-progress .mkpgb-timeright").remove();
$(this.bar+" .mkpgb-title").css({position:"absolute",bottom:"80%",left:"0px",right:"0px",whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis",cursor:"default",color:"#e1e1e1cc"});$(this.bar+" .mkpgb-timeleft").css({marginTop:"10px",color:"#D8D8D8",float:"left"});$(this.bar+" .mkpgb-timeright").css({marginTop:"10px",color:"#D8D8D8",float:"right"});b.minLength=$(b.bar).offset().left;b.maxLength=$(b.bar).width()+b.minLength;$(window).resize(function(){b.minLength=$(b.bar).offset().left;b.maxLength=
$(b.bar).width()+b.minLength});$(b.bar+" .mkpgb-dot").mousedown(function(d){d.preventDefault()});$(b.bar).mousedown(function(d){b.locked||(c=!0);a(d)});$("html").mousemove(function(d){a(d)});$("html").mouseup(function(d){c=!1});b.goto(b.percent)},goto:function(a){a>1&&(a=1);a<0&&(a=0);this.percent=a;$(this.bar+" .mkpgb-dot").css("left",a*100+"%");$(this.bar+" .mkpgb-cur").css("width",a*100+"%");mkPlayer.showtime===!0&&typeof rem.audio!=="undefined"&&$(this.bar+" .mkpgb-timeleft").text(formatSeconds(rem.audio[0].currentTime))},
lock:function(a){a?(this.locked=!0,$(this.bar).addClass("mkpgb-locked")):(this.locked=!1,$(this.bar).removeClass("mkpgb-locked"))}};function formatSeconds(a){var b=0;a=parseInt(a);a>=60&&(b=parseInt(a/60),a=parseInt(a%60));a=(Array(2).join(0)+a).slice(-2);b=(Array(2).join(0)+b).slice(-2);return""+b+":"+a}
document.onkeydown=function(a){if(!(rem.playid===void 0||document.getElementsByClassName("layui-layer").length>0)){var b=a.which||a.keyCode||a.charCode;a=a.ctrlKey||a.metaKey;var c=$("input").is(":focus");b==32&&c==0?pause():a&&b==37?prevMusic():a&&b==39?nextMusic():b==38?(b=rem.audio[0].volume+.05,vBcallback(b)):b==40?(b=rem.audio[0].volume-.05,vBcallback(b)):b==37?(b=(rem.audio[0].currentTime-5)/rem.audio[0].duration,mBcallback(b)):b==39&&(b=(rem.audio[0].currentTime+5)/rem.audio[0].duration,mBcallback(b))}};
function readTextFile(a,b){var c=new XMLHttpRequest;c.onreadystatechange=function(){c.readyState===4&&c.status===200&&b(c.responseText)};c.open("GET",a,!0);c.send()};
